### ISSUE TITLE
version 1.8 coredump at tarantool/src/box/iproto.cc when running conn.eval()

### ISSUE THREAD

**Issue by Fedora7** [tarantool/node-tarantool-driver#38]
connect to console, core dump when running the following from example :

conn.eval('return box.session.user()')
    .then(function(res){
        console.log('current user is:' res[0])
    })

arantool: /home/vbshare/tarantool/src/box/iproto.cc:953: void iproto_msg_decode(iproto_msg*, const char**, const char*, bool*): Assertion `*pos == reqend' failed.
Aborted (core dumped)

gdb backtrace:  

#0  0x00007fd12c1c8428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007fd12c1ca02a in __GI_abort () at abort.c:89
#2  0x00007fd12c1c0bd7 in __assert_fail_base (fmt=<optimized out>, assertion=assertion@entry=0x76e900 "*pos == reqend", file=file@entry=0x76e590 "/home/src/tarantool/src/box/iproto.cc", line=line@entry=953, 
    function=function@entry=0x76ef60 <iproto_msg_decode(iproto_msg*, char const**, char const*, bool*)::__PRETTY_FUNCTION__> "void iproto_msg_decode(iproto_msg*, const char**, const char*, bool*)") at assert.c:92
#3  0x00007fd12c1c0c82 in GI_assert_fail (assertion=0x76e900 "*pos == reqend", file=0x76e590 "/home/src/tarantool/src/box/iproto.cc", line=953, 
    function=0x76ef60 <iproto_msg_decode(iproto_msg*, char const**, char const*, bool*)::__PRETTY_FUNCTION__> "void iproto_msg_decode(iproto_msg*, const char**, const char*, bool*)") at assert.c:101
#4  0x0000000000413091 in iproto_msg_decode (msg=0x7fd1078082a0, pos=0x7fd10cfdf940, reqend=0x7fd107824096 'P' <repeats 200 times>..., stop_input=0x7fd10cfdf94e) at /home/src/tarantool/src/box/iproto.cc:953
#5  0x00000000004123ef in iproto_enqueue_batch (con=0x7fd1078408c0, in=0x7fd1078408c0) at /home/src/tarantool/src/box/iproto.cc:605
#6  0x0000000000412719 in iproto_connection_on_input (loop=0x16e31d0, watcher=0x7fd107840fb8) at /home/src/tarantool/src/box/iproto.cc:706
#7  0x00000000006bd5f4 in ev_invoke_pending (loop=0x16e31d0) at /home/src/tarantool/third_party/libev/ev.c:3347
#8  0x00000000006be4e3 in ev_run (loop=0x16e31d0, flags=0) at /home/src/tarantool/third_party/libev/ev.c:3750
#9  0x00000000005078ce in cord_costart_thread_func (arg=0x16cff70) at /home/src/tarantool/src/fiber.c:1157
#10 0x0000000000506c07 in cord_thread_func (p=0x7fd12501f900) at /home/src/tarantool/src/fiber.c:958
#11 0x00007fd12d4616ba in start_thread (arg=0x7fd10cfff700) at pthread_create.c:333
#12 0x00007fd12c29a41d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

**Comment by hrustbb2** [comment]
and 1.7
