### ISSUE TITLE
Cannot read a space name or space is not defined

### ISSUE THREAD

**Issue by farwayer** [tarantool/node-tarantool-driver#40]
**Tarantool**: 1.9.0
**tarantool-driver**: 2.0.5

```js
...
const res = await db.select('sellOrders', 'id', 100, 0, 'all');
```

```js
Error: Cannot read a space name or space is not defined
    at TarantoolConnection.<anonymous> (.../node_modules/tarantool-driver/lib/connection.js:137:23)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)
```

All ok with number spaceId.

**Comment by farwayer** [comment]
It works with github master version. Is any ETA for releasing 3.0.0?

**Comment by KlonD90** [comment]
Right now ._.
